services:
  target:
    container_name: target
    image: chiefmikey/koa:latest
    networks:
      - inject-net
    ports:
      - 80:8080
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10

  injection:
    container_name: injection
    image: chiefmikey/injection:latest
    networks:
      - inject-net
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      target:
        condition: service_healthy

networks:
  inject-net:
