version = 1
exclude_patterns = [
  "dist",
  "bundle.js",
  "build.js"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[analyzers.meta]
dockerfile_paths = [
  "/alpine-inject",
  "/alpine-craftcms",
  "/alpine-api",
  "/alpine-cassandra"
]