version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "/alpine-inject",
    "/alpine-craftcms",
    "/alpine-api",
    "/alpine-cassandra"
  ]